apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: YTVjYzk2MjZiYTU2YjRjYmQ4YjlhMDdhYTdmZjI4ZmQtMjMzNTk5MDI0LnVzLWVhc3QtMS5lbGIuYW1hem9uYXdzLmNvbQ==
  db_username: YWRtaW4=
  db_password: eW9nZXNoY2hlbm5hYm9pbmE=

